# Generated by Django 5.2.6 on 2025-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tenth_mark',
            new_name='mark_10',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='twelfth_mark',
            new_name='mark_12',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tenth_percentage',
            new_name='percentage_10',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='twelfth_percentage',
            new_name='percentage_12',
        ),
        migrations.AddField(
            model_name='student',
            name='ug_cgpa',
            field=models.FloatField(default=0.34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ug_passed_out',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence'), ('BT', 'Botony'), ('CH', 'Chemistry'), ('PH', 'Physics')], max_length=50),
        ),
    ]
