# Generated by Django 5.2.6 on 2025-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_tenth_mark_student_mark_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence'), ('BT', 'Botany'), ('CH', 'Chemistry'), ('PH', 'Physics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_10',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage_12',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
