# Generated by Django 5.2.6 on 2025-09-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_age_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('AI', 'Artificial Intelligence'), ('BT', 'Botany'), ('CH', 'Chemistry'), ('PH', 'Physics')], max_length=50),
        ),
    ]
